posts: Articles
category: Catégorie
categories: Catégories
tag: Activité
tags: Activités
archives: Archives
about: Profil
friends: Amis
startRead: Découvrir
recommendedPosts: Articles conseillés
publishDate: Date de publication
readCount: Nombre de lectures
wordCount: Total de mots
readTimes: Temps de lecture
Minutes: Min
readMore: Lire plus
toc: TOC
reprint: Reprint please specify
curr: Courant
prev: Précédent
next: Suivant
search: Rechercher
searchTip: Entrez un mot-clé
postTagTitle: Activités
postCategoryTitle: Catégories
categoryRadarTitle: Graphe à catégories
categoryNumber: Number of Categories
categoryEmptyTip: Your posts has no categories information yet.
postCharts: Post Charts
postPublishChart: Post Publish Chart
categoriesChart: Categories Chart
top10TagsChart: TOP10 Tags Chart
postsNumberName: Number of posts
maximum: Maximum
minimum: Minimum
average: Moyenne
myProjects: Mes projets
mySkills: Mes compétences
otherSkills: Compétences techniques
gallery: Galerie
from: De
author: Auteur
link: Lien
notag: No tag
