posts: Articles
category: Catégorie
categories: Catégories
tag: Tag
tags: Tags
archives: Archives
about: A propos
friends: Amis
startRead: Découvrir
recommendedPosts: Articles conseillés
publishDate: Date de publication
readCount: Nombre de lectures
wordCount: Total de mots
readTimes: Temps de lecture
Minutes: Min
readMore: Lire plus
toc: TOC
reprint: Reprint please specify
curr: Courant
prev: Précédent
next: Suivant
search: Rechercher
searchTip: Entrez un mot-clé
postTagTitle: Post Tags
postCategoryTitle: Post Categories
categoryRadarTitle: Post Categories Radar Chart
categoryNumber: Number of Categories
categoryEmptyTip: Your posts has no categories information yet.
postCharts: Post Charts
postPublishChart: Post Publish Chart
categoriesChart: Categories Chart
top10TagsChart: TOP10 Tags Chart
postsNumberName: Number of posts
maximum: Maximum
minimum: Minimum
average: Moyenne
myProjects: Mes projets
mySkills: Mes compétences
otherSkills: Autres compétences
gallery: Galerie
from: De
author: Auteur
link: Lien
notag: No tag
